# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

defaults: &defaults
  open_weather_app_id: de547bb6fac5e67de75f537f834f44dd

development:
  <<: *defaults
  secret_key_base: cc575679fe676a557752ad30d5d5744f1f2d286a5194554e92e8fe233e71534ba396adec4b54f6ac0ce4c7e519cd825c8c7282155c71042ddc129ef8e0d037ca

test:
  <<: *defaults
  secret_key_base: 9913cbfd48572843ed3e79df451fbdc46e5ac683098fe98afb01a36a78c88ee9a19944393e57d18c140747296a28270cd0d689f5c51cdcb6341b929c77fe08e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
